# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: ubuntu-latest

stages:
- stage: SAST
  jobs:
  - job: SASTWork
    displayName: 'SAST Work'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'pom'
- stage: SCA
  jobs:
  - job: SCAtWork
    displayName: 'SCA Work'
    steps:
    - script: "Do SCA work"

- stage: ContainerSecurity
  jobs:
  - job: ContainerSecurityWork
    displayName: 'Container Security Work'
    steps:
    - script: "Do Container Security work"
